# Generated by Django 4.2.3 on 2024-03-03 18:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fayl_turi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turi', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Jurnallar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=1000)),
                ('slug', models.SlugField(max_length=1000)),
                ('Text', models.TextField()),
                ('fayl', models.FileField(upload_to='news/fayllar')),
                ('chopetilishVaqti', models.DateTimeField(default=django.utils.timezone.now)),
                ('yaratilganVaqti', models.DateTimeField(auto_now_add=True)),
                ('ozgarishVaqti', models.DateTimeField(auto_now=True)),
                ('holati', models.CharField(choices=[('QR', 'qoralama'), ('CHP', 'chopetilish')], default='QR', max_length=3)),
                ('kategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.fayl_turi')),
            ],
            options={
                'ordering': ['-chopetilishVaqti'],
            },
        ),
    ]
