# Generated by Django 4.2.3 on 2024-03-03 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jurnallar',
            name='rasm',
            field=models.ImageField(default=2, upload_to='news/images'),
            preserve_default=False,
        ),
    ]
