# Generated by Django 4.2.3 on 2024-03-04 17:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_jurnallar_rasm'),
    ]

    operations = [
        migrations.CreateModel(
            name='Yangiliklar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=1000)),
                ('slug', models.SlugField(max_length=1000)),
                ('Text', models.TextField()),
                ('rasm', models.ImageField(upload_to='news/images')),
                ('chopetilishVaqti', models.DateTimeField(default=django.utils.timezone.now)),
                ('yaratilganVaqti', models.DateTimeField(auto_now_add=True)),
                ('ozgarishVaqti', models.DateTimeField(auto_now=True)),
                ('holati', models.CharField(choices=[('QR', 'qoralama'), ('CHP', 'chopetilish')], default='QR', max_length=3)),
            ],
            options={
                'ordering': ['-chopetilishVaqti'],
            },
        ),
    ]
