# Generated by Django 5.0.2 on 2024-03-18 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_yangiliklar'),
    ]

    operations = [
        migrations.AddField(
            model_name='yangiliklar',
            name='mainNew',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='jurnallar',
            name='holati',
            field=models.CharField(choices=[('QR', 'qoralama'), ('CHP', 'chopetilish')], default='CHP', max_length=3),
        ),
    ]
