# Generated by Django 4.2.7 on 2024-03-26 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_yangiliklar_mainnew_alter_jurnallar_holati'),
    ]

    operations = [
        migrations.RenameField(
            model_name='yangiliklar',
            old_name='Text',
            new_name='text',
        ),
    ]
