# Generated by Django 4.2.7 on 2024-05-13 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_rename_text_yangiliklar_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tahririyat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birinchiUstun', models.CharField(max_length=400)),
                ('ikkinchiUstun', models.CharField(max_length=400)),
                ('uchinchiUstun', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Talablar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=300)),
                ('asosiyQism', models.TextField()),
            ],
        ),
    ]
